export const USER_SIGNIN_ATTEMPT = 'USER_SIGNIN_ATTEMPT';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';

export const USER_SIGNOUT_SUCCESS = 'USER_SIGNOUT_SUCCESS';
